// Copyright (c) Dolittle. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import React from 'react';

import {
    AddBoxRounded,
    AddCircle,
    AppsRounded,
    ArrowBack,
    ArrowDropDownRounded,
    ArrowDropUpRounded,
    BackupRounded,
    CancelRounded,
    CheckRounded,
    CheckCircleRounded,
    ChevronRight,
    CloseRounded,
    CloudRounded,
    CopyAllRounded,
    DeleteRounded,
    DescriptionRounded,
    DownloadRounded,
    DnsRounded,
    EditRounded,
    EmailRounded,
    ErrorRounded,
    Explore,
    ExpandCircleDownRounded,
    ExpandMore,
    ExpandLess,
    FindInPageRounded,
    HelpRounded,
    HexagonRounded,
    HomeRounded,
    InsightsRounded,
    KeyboardDoubleArrowLeft,
    KeyboardDoubleArrowRight,
    LogoutRounded,
    MenuRounded,
    MessageRounded,
    MoreVertRounded,
    PolylineRounded,
    RefreshRounded,
    RestartAltRounded,
    RocketLaunch,
    SaveRounded,
    Search,
    SettingsRounded,
    SupervisedUserCircleRounded,
    TextSnippetRounded,
    UploadRounded,
    Visibility,
    VisibilityOff,
    WarningRounded,
} from '@mui/icons-material';

import { AigonixLightCube, AigonixLightLogo, Bridge, Dolittle, ContainerRegistry } from './CustomIcons';

export type SvgIconsDefinition = keyof typeof SvgIcons;

export const SvgIcons = {
    AddBoxRounded: <AddBoxRounded />,
    AddCircle: <AddCircle />,
    AigonixLightCube: <AigonixLightCube />,
    AigonixLightLogo: <AigonixLightLogo />,
    AppsRounded: <AppsRounded />,
    ArrowBack: <ArrowBack />,
    ArrowDropDownRounded: <ArrowDropDownRounded />,
    ArrowDropUpRounded: <ArrowDropUpRounded />,
    BackupRounded: <BackupRounded />,
    Bridge: <Bridge />,
    CancelRounded: <CancelRounded />,
    ContainerRegistry: <ContainerRegistry />,
    CheckCircleRounded: <CheckCircleRounded />,
    CheckRounded: <CheckRounded />,
    ChevronRight: <ChevronRight />,
    CloseRounded: <CloseRounded />,
    CloudRounded: <CloudRounded />,
    CopyAllRounded: <CopyAllRounded />,
    DeleteRounded: <DeleteRounded />,
    DescriptionRounded: <DescriptionRounded />,
    Dolittle: <Dolittle />,
    DownloadRounded: <DownloadRounded />,
    DnsRounded: <DnsRounded />,
    EditRounded: <EditRounded />,
    EmailRounded: <EmailRounded />,
    ErrorRounded: <ErrorRounded />,
    Explore: <Explore />,
    ExpandCircleDownRounded: <ExpandCircleDownRounded />,
    ExpandMore: <ExpandMore />,
    ExpandLess: <ExpandLess />,
    FindInPageRounded: <FindInPageRounded />,
    HelpRounded: <HelpRounded />,
    HexagonRounded: <HexagonRounded />,
    HomeRounded: <HomeRounded />,
    InsightsRounded: <InsightsRounded />,
    KeyboardDoubleArrowLeft: <KeyboardDoubleArrowLeft />,
    KeyboardDoubleArrowRight: <KeyboardDoubleArrowRight />,
    LogoutRounded: <LogoutRounded />,
    MenuRounded: <MenuRounded />,
    MessageRounded: <MessageRounded />,
    MoreVertRounded: <MoreVertRounded />,
    PolylineRounded: <PolylineRounded />,
    RefreshRounded: <RefreshRounded />,
    RestartAltRounded: <RestartAltRounded />,
    RocketLaunch: <RocketLaunch />,
    SaveRounded: <SaveRounded />,
    Search: <Search />,
    SettingsRounded: <SettingsRounded />,
    SupervisedUserCircleRounded: <SupervisedUserCircleRounded />,
    TextSnippetRounded: <TextSnippetRounded />,
    UploadRounded: <UploadRounded />,
    Visibility: <Visibility />,
    VisibilityOff: <VisibilityOff />,
    WarningRounded: <WarningRounded />,
};

export const availableIcons = Object.keys(SvgIcons);
