version: '2'
services:
    server:
        build: .
        command: yarn ts-node index.ts
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - '3008:3008'
        environment:
            WH_AUTHORIZATION: 'Basic bTM6am9obmNhcm1hY2s='
            MONGODB_URI: 'mongodb://mongo:27017/local'
    mongo:
        labels:
            - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
        image: dolittle/mongodb:4.2.2
        ports:
            - 27018:27017
