version: '3.1'
services:
  studio-mongo:
    image: dolittle/mongodb:4.2.2
    ports:
      - 27017:27017
    logging:
      driver: none

  studio-ingress:
    image: nginx:1.18.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    restart: on-failure
    logging:
      driver: none

  studio-runtime-portal:
    image: dolittle/runtime:5.1.4
    volumes:
      - ./Portal/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9700:9700
      - 50052:50052
      - 50053:50053

  studio-runtime-k8s-mock:
    image: dolittle/runtime:5.1.4
    volumes:
      - ./K8sMock/resources.json:/app/.dolittle/resources.json
      - ./K8sMock/event-horizon-consents.json:/app/.dolittle/event-horizon-consents.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9701:9700
      - 50054:50052
      - 50055:50053

  studio-runtime-applications:
    image: dolittle/runtime:5.1.4
    volumes:
      - ./Applications/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9702:9700
      - 50056:50052
      - 50057:50053

  studio-runtime-events:
    image: dolittle/runtime:5.1.4
    volumes:
      - ./Events/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9703:9700
      - 50058:50052
      - 50059:50053

  studio-runtime-microservices:
    image: dolittle/runtime:5.1.4
    volumes:
      - ./Microservices/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9704:9700
      - 50060:50052
      - 50061:50053
