version: '3.1'
services:
  ingress:
    image: nginx:1.18.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    restart: on-failure
#    logging:
#      driver: none

