apiVersion: v1
kind: PersistentVolume
metadata:
  name: managed-premium
  labels:
    type: local
spec:
  storageClassName: managed-premium
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvolume"
