---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    dolittle.io/tenant-id: 453e04a7-4f9d-42f2-b36c-d51fa2c83fa3
    dolittle.io/application-id: 11b6cf47-5d9f-438f-8116-0d9828654657
  labels:
    tenant: Customer-Chris
    application: Taco
    environment: Dev
  name: dev-tenants
  namespace: application-11b6cf47-5d9f-438f-8116-0d9828654657
data:
  tenants.json: |
    {
      "17426336-fb8e-4425-8ab7-07d488367be9": {}
    }
