version: '3.1'
services:
  studio-mongo:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/mongodb:4.2.2
    ports:
      - 27017:27017

  studio-ingress:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: nginx:1.18.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    restart: on-failure

  studio-runtime-portal:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/runtime:5.3.2
    volumes:
      - ./Portal/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9701:9700
      - 50052:50052
      - 50053:50053

  studio-runtime-applications:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/runtime:5.3.2
    volumes:
      - ./Applications/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9702:9700
      - 50054:50052
      - 50055:50053

  studio-runtime-events:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/runtime:5.3.2
    volumes:
      - ./Events/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9703:9700
      - 50056:50052
      - 50057:50053

  studio-runtime-k8s:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/runtime:5.3.2
    volumes:
      - ./K8s/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9704:9700
      - 50058:50052
      - 50059:50053

  studio-runtime-data:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/runtime:5.3.2
    volumes:
      - ./Data/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9705:9700
      - 50060:50052
      - 50061:50053

  studio-runtime-businessmomentsadapters:
    labels:
      - dolittle="fe7736bb-57fc-4166-bb91-6954f4dd4eb7"
    image: dolittle/runtime:5.3.2
    volumes:
      - ./BusinessMomentsAdapters/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9705:9700
      - 50062:50052
      - 50063:50053

