name: Bridge - Frontend

on:
  push:

env:
  SOURCE_PATH: "Source/Bridge/bridge-frontend"
  DOCKER_FILE: "Source/Bridge/bridge-frontend/Dockerfile"
  DOCKER_IMAGE_TAG: "${{ secrets.BRIDGE_CONTAINER_REGISTRY_ENDPOINT }}/bridge-frontend"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '${{ env.SOURCE_PATH }}/**'
              - 'Source/DesignSystem/**'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn

      - name: CI
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn build

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.BRIDGE_CONTAINER_REGISTRY_ENDPOINT }}
          username: ${{ secrets.BRIDGE_REGISTRY_USERNAME }}
          password: ${{ secrets.BRIDGE_REGISTRY_PASSWORD }}


      - name: Get git branch name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
        id: get_branch

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_IMAGE_TAG }}:${{ steps.get_branch.outputs.branch }}
