name: Build SelfService Backend

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/SelfService/Backend/**"
      - ".github/workflows/build-selfservice-backend.yml"

env:
  CONTAINER_REGISTRY: 508c17455f2a4b4cb7a52fbb1484346d.azurecr.io
  DOCKER_IMAGE_TAG: "dolittle/studio/self-service"
  DOCKER_FILE: "Source/SelfService/Backend/Dockerfile"
  BACKEND: "Source/SelfService/Backend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go version

      - name: Login via Az module
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Get the version
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: What is the tag?
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build Docker image
        working-directory: ${{ env.BACKEND }}
        run: |
          docker build .  --tag ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_TAG }}:${{ steps.vars.outputs.sha_short }}

      - name: Push Docker image
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_TAG }}:${{ steps.vars.outputs.sha_short }}
