name: Build SelfService Backend

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/SelfService/Backend/**"

env:
  CONTAINER_REGISTRY: 508c17455f2a4b4cb7a52fbb1484346d.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go version

      - name: Login via Az module
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Image digest
        run: echo ${{ steps.vars.outputs.tag }}
