name: Build Events

on:
  push:
    branches:
    - '**'
    paths:
    - 'Source/Events/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.has-changes == 'true' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node v12
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
    - name: Build
      run: |
        yarn
        cd Source/Events/Backend
        yarn build
        cd ../Web
        yarn build
