name: Build Portal

on:
  push:
    branches:
    - '**'
    paths:
    - 'Source/Portal/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node v12
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
    - name: Build
      run: |
        yarn
        cd Source/Portal/Backend
        yarn ci
        cd ../Web
        yarn build
