name: CI - SelfService - Backend

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/SelfService/Backend/**"
      - ".github/workflows/selfservice-backend.yml"

env:
  SOURCE_PATH: "Source/SelfService/Backend"
  DOCKER_FILE: "Source/SelfService/Backend/Dockerfile"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - name: Build
        working-directory: ${{ env.SOURCE_PATH}}
        run: go build .

      - name: Test
        working-directory: ${{ env.SOURCE_PATH}}
        run: go test -v ./...

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ${{ env.SOURCE_PATH }}
          file: ./${{ env.DOCKER_FILE }}
