name: Design System

on:
  push:

env:
  SOURCE_PATH: "Source/DesignSystem"

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '${{ env.SOURCE_PATH }}/**'
              - 'Source/Shared/**'
              - .github/workflows/designsystem*

      - name: Setup node
        uses: actions/setup-node@v1
        if: steps.filter.outputs.src == 'true'
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        if: steps.filter.outputs.src == 'true'
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn

      - name: CI
        if: steps.filter.outputs.src == 'true'
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn ci
