name: Design System

on:
  push:

env:
  SOURCE_PATH: "Source/DesignSystem"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '${{ env.SOURCE_PATH }}/**'
              - 'Source/Shared/**'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn

      - name: CI
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn ci
