name: Dev - Applications - Build

on:
  push:
    branches:
    - 'development'
    paths:
    - 'Source/Applications/**'
  pull_request:
    branches:
    - 'development'
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.has-changes == 'true' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node v12
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
    - name: Build
      run: |
        yarn
        cd Source/Applications/Backend
        yarn build
        cd ../Web
        yarn build
