name: SelfService - Backend

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/SelfService/Backend/**"
      - ".github/workflows/selfservice-backend.yml"

env:
  SOURCE_PATH: "Source/SelfService/Backend"
  DOCKER_FILE: "Source/SelfService/Backend/Dockerfile"
  DOCKER_IMAGE_TAG: "dolittle/self-service-backend"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - name: Build
        working-directory: ${{ env.SOURCE_PATH}}
        run: go build .

      - name: Test
        working-directory: ${{ env.SOURCE_PATH}}
        run: go test -v ./...

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ${{ env.SOURCE_PATH }}
          file: ./${{ env.DOCKER_FILE }}

      - name: Get git branch name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
        id: get_branch

      - name: Get git sha short
        id: get_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ env.SOURCE_PATH }}
          file: ./${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_IMAGE_TAG }}:${{ steps.get_branch.outputs.branch }}-${{ steps.get_sha.outputs.sha_short }}
