name: SelfService - Backend Mock

on:
  push:
    branches-ignore:
      - main
    paths:
      - "Source/SelfService/BackendMock/**"
      - "Source/Shared/**"
      - ".github/workflows/selfservice-backend-mock.yml"

env:
  SOURCE_PATH: "Source/SelfService/BackendMock"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn

      - name: CI
        working-directory: ${{ env.SOURCE_PATH}}
        run: yarn ci
